server:
  port: 9092

eureka:
  instance:
    hostname: localhost
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://eurekaservice:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userservicefallback

        - id: product-service
          uri: lb://product-service
          predicates:
           - Path=/api/v2/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productservicefallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillieSeconds: 5000

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

