FROM openjdk:11


ADD target/ServiceRegistryMicroservice-0.0.1-SNAPSHOT.jar ServiceRegistryMicroservice-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "ServiceRegistryMicroservice-0.0.1-SNAPSHOT.jar"]